### PR TITLE
Update Microsoft.Build.Tasks.Core package version to 17.9.5

### PR DESCRIPTION
**Pull request by NikolaMilosavljevic**
https://github.com/dotnet/deployment-tools/pull/373 has updated the version of `Microsoft.Build.Tasks.Core` package to 17.8.3.

This causes issues with `dotnet mage` signing step. Example output:

```
dotnet mage -sign files\app.manifest -cf test.pfx -pwd <password>

Internal error, please try again. Could not create hash algorithm object. If the application has been trimmed, ensure the required algorithm implementations are preserved.
   at Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFileInternal(X509Certificate2 cert, Uri timestampUrl, String path, Boolean targetFrameworkSupportsSha256, ResourceManager resources, Boolean disallowMansignTimestampFallback)
   at Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(X509Certificate2 cert, Uri timestampUrl, String path)
   at Microsoft.Deployment.MageCLI.Command.ExecuteManifestRelated() in D:\git2\deployment-tools\src\clickonce\MageCLI\Command.cs:line 1407
   at Microsoft.Deployment.MageCLI.Command.Execute() in D:\git2\deployment-tools\src\clickonce\MageCLI\Command.cs:line 1458
   at Microsoft.Deployment.MageCLI.Application.Main(String[] args) in D:\git2\deployment-tools\src\clickonce\MageCLI\Application.cs:line 44
```

Updating to 17.9.5 which has a fix.

@John-Hart @sujitnayak is this a known issue in newer versions of this package?

### CODE REVIEW

**Comment by MichaelSimons** [comment]
Can a test be added to prevent this type of regression going forward?

**Comment by NikolaMilosavljevic** [comment]
> Can a test be added to prevent this type of regression going forward?

Yes - I am creating an issue to track adding relevant tests.

**Comment by sujitnayak** [comment]
@NikolaMilosavljevic 
The ClickOnce team hasn't touched the signing piece in a while I think. Last change to SignFile was from @YuliiaKovalova on 4/19. Does that line up with the version you're updating to?

**Comment by NikolaMilosavljevic** [comment]
> Microsoft.Build.Tasks.Core

`17.0.0` was published on 11/8/2021. `17.8.3` on 11/14/2023. Any change in between might have caused this. I have not tested any other versions newer than `17.0.0`.

**Comment by YuliiaKovalova** [comment]
@NikolaMilosavljevic , the fix is a part of vs17.9 branch: (https://github.com/dotnet/msbuild/blob/vs17.9/src/Tasks/ManifestUtil/mansign2.cs) and wasn't backported to earlier versions.
Could you please try the version 17.9.5?

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic , the fix is a part of vs17.9 branch: (https://github.com/dotnet/msbuild/blob/vs17.9/src/Tasks/ManifestUtil/mansign2.cs) and wasn't backported to earlier versions. Could you please try the version 17.9.5?

Thank you! I have tested 17.9.5 and it works fine. I have updated this PR and description/title.

**Comment by NikolaMilosavljevic** [comment]
@sujitnayak @YuliiaKovalova @joeloff can I get a review for this small change?

**Review by sujitnayak — APPROVED** [review]

**Pull request merged**
