### PR TITLE
Set default URL to point to CDN

### LINKED ISSUE #104: Releases.json should reference CDN
The releases.json ProductCollection is referencing the blob storage URL directly instead of using the CDN URL, https://dotnetcli.azureedge.net/dotnet/release-metadata/releases-index.json

### PR DESCRIPTION
**Pull request by joeloff**
Fixes #104

### CODE REVIEW

**Comment by joeloff** [comment]
@leecow, @rbhanda  could I get an ack on the CDN change

**Comment by leecow** [comment]
New URL looks good to me, and resolves correctly, but I would like @rbhanda to sign-off.

**Review by rbhanda — APPROVED** [review]

**Comment by rbhanda** [comment]
LGTM

**Pull request merged**
