### PR TITLE
[Loc] Loc update

### PR DESCRIPTION
**Pull request by cristianosuzuki77**
@NikolaMilosavljevic  Updating/fixing few previous translations.

### CODE REVIEW

**Review by NikolaMilosavljevic — APPROVED** [review]
Please note that we have an issue ([https://github.com/dotnet/deployment-tools/issues/77](url)) that is causing some build errors and your PR validations will not succeed.

**Comment by cristianosuzuki77** [comment]
@NikolaMilosavljevic Could you point to the error log statement? By clicking on 'Details' above I am not able to see the problematic changes.

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic Could you point to the error log statement? By clicking on 'Details' above I am not able to see the problematic changes.

This PR has checks that are failing, but that's expected due to the issue I linked in my previous comment.

**Comment by cristianosuzuki77** [comment]
@NikolaMilosavljevic  The link doesn't render to me (I get a 404). Let me know if I need to do anything or just wait.

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic The link doesn't render to me (I get a 404). Let me know if I need to do anything or just wait.

This PR can be merged.

**Pull request merged**
