### PR TITLE
Update arcade and implement source-build CI

### PR DESCRIPTION
**Pull request by lbussell**
Part 2 of https://github.com/dotnet/source-build/issues/2365

To make sure ArPow (arcade-powered source-build) keeps working in this repo, we need to add it to PR validation. We also need it to run in the official build to publish source-built artifacts that can be tested downstream.

See <https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/onboarding/ci-onboarding.md> for ArPow CI onboarding info.

For more info about ArPow see <https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/implementation-plan.md>.

### CODE REVIEW

**Review by crummel — APPROVED** [review]

**Comment by NikolaMilosavljevic** [comment]
@lbussell was Arcade tooling (everything under eng/common) updated using automated dependency flow (i.e. Darc tool)?

**Comment by lbussell** [comment]
> @lbussell was Arcade tooling (everything under eng/common) updated using automated dependency flow (i.e. Darc tool)?

@NikolaMilosavljevic  No, I manually copied it from here: https://github.com/dotnet/arcade/tree/main/eng/common because it didn't look to me like this repo had any automation set up. I also opened an issue for creating a Darc subscription here: https://github.com/dotnet/deployment-tools/issues/134

**Comment by NikolaMilosavljevic** [comment]
> > @lbussell was Arcade tooling (everything under eng/common) updated using automated dependency flow (i.e. Darc tool)?
> 
> @NikolaMilosavljevic No, I manually copied it from here: https://github.com/dotnet/arcade/tree/main/eng/common because it didn't look to me like this repo had any automation set up. I also opened an issue for creating a Darc subscription here: #134

I've used the following command in the past for updating Arcade tooling - would that produce the expected results?

```
darc update-dependencies --channel ".net 5 eng"
```

**Comment by NikolaMilosavljevic** [comment]
> > > @lbussell was Arcade tooling (everything under eng/common) updated using automated dependency flow (i.e. Darc tool)?
> > 
> > 
> > @NikolaMilosavljevic No, I manually copied it from here: https://github.com/dotnet/arcade/tree/main/eng/common because it didn't look to me like this repo had any automation set up. I also opened an issue for creating a Darc subscription here: #134
> 
> I've used the following command in the past for updating Arcade tooling - would that produce the expected results?
> 
> ```
> darc update-dependencies --channel ".net 5 eng"
> ```

Regardless, if this is passing all the tests, we should be OK.

**Review by NikolaMilosavljevic — APPROVED** [review]

**Comment by lbussell** [comment]
> ```
> darc update-dependencies --channel ".net 5 eng"
> ```

I tried this command and it did update to the latest dependencies, but the repo is still on 5.0 so the arcade tooling is still older. I needed a feature from a newer version of the tooling, the `skipPublishValidation` option for the source-build CI template: https://github.com/dotnet/arcade/blob/fe787bd48ed72e51a98eb5e4e5e5af74edb531e5/eng/common/templates/job/source-build.yml#L18

**Comment by NikolaMilosavljevic** [comment]
> > ```
> > darc update-dependencies --channel ".net 5 eng"
> > ```
> 
> I tried this command and it did update to the latest dependencies, but the repo is still on 5.0 so the arcade tooling is still older. I needed a feature from a newer version of the tooling, the `skipPublishValidation` option for the source-build CI template: https://github.com/dotnet/arcade/blob/fe787bd48ed72e51a98eb5e4e5e5af74edb531e5/eng/common/templates/job/source-build.yml#L18. Otherwise, the repo still tries to publish a package during source-build CI and fails.

It's possible that we need to update the channel name in this command. But, I'm OK with manual update of Arcade for this PR.

**Review by MichaelSimons — APPROVED** [review]

**Pull request merged**
